// packages/framework-scanners/src/extractors/react-extractor.ts
import { createHash } from 'node:crypto';
import * as nodePath from 'node:path';
import * as ts from 'typescript';
import { EdgeKind, NodeKind, type IEdge, type INode } from '@shrkcrft/graph';
import type {
  IExtractInput,
  IExtractOutput,
  IFrameworkExtractor,
} from '../extractor-api/framework-extractor.ts';

export const REACT_EXTRACTOR_SOURCE = 'react-extractor@v1';

const HOOK_NAME_RE = /^use[A-Z]/;

const FAST_FILTER_NEEDLES = [
  "from 'react'",
  'from "react"',
  "from 'react/jsx-runtime'",
  'jsx',
  'React.FC',
  'createElement',
];

/**
 * React extractor.
 *
 * Heuristic detection (no full type information):
 *   - **Component**: top-level function / arrow function / class
 *     declaration whose name starts with an uppercase letter AND whose
 *     body contains a JSX element. False positives in TSX are filtered
 *     by the JSX-presence check.
 *   - **Hook usage**: any CallExpression whose callee identifier
 *     matches `/^use[A-Z]/`. Recorded as a single hook-usage entity
 *     per (file, hook name) pair.
 *
 * Emits FrameworkDeclares edges from file → entity, and UsesHook edges
 * from component → hook-usage entity when both can be co-located.
 */
export const reactExtractor: IFrameworkExtractor = {
  framework: 'react',
  label: 'React',
  fileMatches({ path, content }) {
    if (!/\.(?:t|j)sx?$/.test(path)) return false;
    // Cheap pre-filter: skip files that show no sign of React.
    const lower = content;
    for (const needle of FAST_FILTER_NEEDLES) {
      if (lower.includes(needle)) return true;
    }
    return false;
  },
  extract(input): IExtractOutput {
    const nodes: INode[] = [];
    const edges: IEdge[] = [];
    const sf = parse(input);
    if (!sf) return { nodes, edges };

    const components: { id: string; name: string; node: ts.Node }[] = [];
    const hookNames = new Set<string>();

    // First pass: identify components at the top level.
    for (const stmt of sf.statements) {
      visitTopLevel(stmt, input, components);
    }

    // Second pass: walk every node, collect hook usages, attribute them
    // to enclosing components when possible.
    const enclosingComponent = (n: ts.Node): string | undefined => {
      for (const c of components) {
        if (isAncestor(c.node, n)) return c.id;
      }
      return undefined;
    };
    const visit = (n: ts.Node): void => {
      if (ts.isCallExpression(n) && ts.isIdentifier(n.expression) && HOOK_NAME_RE.test(n.expression.text)) {
        const hookName = n.expression.text;
        hookNames.add(hookName);
        const compId = enclosingComponent(n);
        if (compId) {
          const hookId = `framework:react:hook-usage:${input.filePath}#${hookName}`;
          edges.push(edge(compId, hookId, EdgeKind.UsesHook, { hook: hookName }));
        }
      }
      ts.forEachChild(n, visit);
    };
    ts.forEachChild(sf, visit);

    for (const c of components) {
      const node: INode = {
        id: c.id,
        kind: NodeKind.FrameworkEntity,
        label: c.name,
        path: input.filePath,
        tags: ['react', 'component'],
        data: { framework: 'react', subtype: 'component', name: c.name },
      };
      nodes.push(node);
      edges.push(edge(input.fileNodeId, c.id, EdgeKind.FrameworkDeclares, { subtype: 'component' }));
    }
    for (const hook of hookNames) {
      const node: INode = {
        id: `framework:react:hook-usage:${input.filePath}#${hook}`,
        kind: NodeKind.FrameworkEntity,
        label: hook,
        path: input.filePath,
        tags: ['react', 'hook-usage'],
        data: { framework: 'react', subtype: 'hook-usage', hook },
      };
      nodes.push(node);
      edges.push(edge(input.fileNodeId, node.id, EdgeKind.FrameworkDeclares, { subtype: 'hook-usage' }));
    }
    return { nodes, edges };
  },
};

function visitTopLevel(
  stmt: ts.Node,
  input: IExtractInput,
  out: { id: string; name: string; node: ts.Node }[],
): void {
  // export const Foo = () => <div />;
  if (ts.isVariableStatement(stmt)) {
    for (const decl of stmt.declarationList.declarations) {
      if (!ts.isIdentifier(decl.name)) continue;
      const name = decl.name.text;
      if (!/^[A-Z]/.test(name)) continue;
      const init = decl.initializer;
      if (!init) continue;
      if (containsJsx(init)) {
        out.push({ id: makeComponentId(input.filePath, name), name, node: init });
      }
    }
    return;
  }
  // function Foo() { return <div />; }
  if (ts.isFunctionDeclaration(stmt) && stmt.name && /^[A-Z]/.test(stmt.name.text)) {
    if (containsJsx(stmt)) {
      out.push({ id: makeComponentId(input.filePath, stmt.name.text), name: stmt.name.text, node: stmt });
    }
    return;
  }
  // export default function Foo() {}
  if (ts.isExportAssignment(stmt) && ts.isFunctionExpression(stmt.expression)) {
    const name = stmt.expression.name?.text ?? 'Default';
    if (/^[A-Z]/.test(name) && containsJsx(stmt.expression)) {
      out.push({ id: makeComponentId(input.filePath, name), name, node: stmt.expression });
    }
    return;
  }
  // class Foo extends React.Component { render() { return <div />; } }
  if (ts.isClassDeclaration(stmt) && stmt.name && /^[A-Z]/.test(stmt.name.text)) {
    if (extendsComponent(stmt) || containsJsx(stmt)) {
      out.push({ id: makeComponentId(input.filePath, stmt.name.text), name: stmt.name.text, node: stmt });
    }
    return;
  }
}

function containsJsx(node: ts.Node): boolean {
  let found = false;
  const visit = (n: ts.Node): void => {
    if (found) return;
    if (ts.isJsxElement(n) || ts.isJsxSelfClosingElement(n) || ts.isJsxFragment(n)) {
      found = true;
      return;
    }
    ts.forEachChild(n, visit);
  };
  visit(node);
  return found;
}

function extendsComponent(cls: ts.ClassDeclaration): boolean {
  if (!cls.heritageClauses) return false;
  for (const h of cls.heritageClauses) {
    if (h.token !== ts.SyntaxKind.ExtendsKeyword) continue;
    for (const t of h.types) {
      const text = t.expression.getText();
      if (text === 'Component' || text === 'React.Component' || text === 'PureComponent' || text === 'React.PureComponent') {
        return true;
      }
    }
  }
  return false;
}

function isAncestor(ancestor: ts.Node, descendant: ts.Node): boolean {
  let cur: ts.Node | undefined = descendant;
  while (cur) {
    if (cur === ancestor) return true;
    cur = cur.parent;
  }
  return false;
}

function makeComponentId(path: string, name: string): string {
  return `framework:react:component:${path}#${name}`;
}

function edge(
  from: string,
  to: string,
  kind: EdgeKind,
  data?: Readonly<Record<string, unknown>>,
): IEdge {
  return {
    id: createHash('sha1').update(`${from}|${to}|${kind}`).digest('hex'),
    from,
    to,
    kind,
    source: REACT_EXTRACTOR_SOURCE,
    ...(data ? { data } : {}),
  };
}

function parse(input: IExtractInput): ts.SourceFile | undefined {
  const ext = nodePath.extname(input.filePath).toLowerCase();
  const kind =
    ext === '.tsx' ? ts.ScriptKind.TSX
    : ext === '.jsx' ? ts.ScriptKind.JSX
    : ext === '.js' || ext === '.mjs' || ext === '.cjs' ? ts.ScriptKind.JS
    : ts.ScriptKind.TS;
  try {
    return ts.createSourceFile(input.filePath, input.content, ts.ScriptTarget.Latest, true, kind);
  } catch {
    return undefined;
  }
}

// packages/framework-scanners/src/extractors/angular-extractor.ts
import { createHash } from 'node:crypto';
import * as nodePath from 'node:path';
import * as ts from 'typescript';
import { EdgeKind, NodeKind, type IEdge, type INode } from '@shrkcrft/graph';
import type {
  IExtractInput,
  IExtractOutput,
  IFrameworkExtractor,
} from '../extractor-api/framework-extractor.ts';

export const ANGULAR_EXTRACTOR_SOURCE = 'angular-extractor@v1';

const FAST_FILTER_NEEDLES = [
  "from '@angular/core'",
  'from "@angular/core"',
  '@Component',
  '@Directive',
  '@NgModule',
  '@Injectable',
  '@Pipe',
];

const DECORATOR_TO_SUBTYPE: Readonly<Record<string, string>> = {
  Component: 'component',
  Directive: 'directive',
  Pipe: 'pipe',
  Injectable: 'service',
  NgModule: 'module',
};

/**
 * Angular extractor.
 *
 * Detects classes carrying any of the @Component / @Directive / @Pipe /
 * @Injectable / @NgModule decorators. Emits one `FrameworkEntity` per
 * decorated class, with the subtype derived from the decorator name.
 *
 * Component-specific metadata (selector, standalone, templateUrl) is
 * lifted into `data` so the agent / dashboard can render it without a
 * second AST walk.
 *
 * Out of scope (Wave 7 follow-up): template parsing, DI graph between
 * services, route configurations. Each is its own pass.
 */
export const angularExtractor: IFrameworkExtractor = {
  framework: 'angular',
  label: 'Angular',
  fileMatches({ path, content }) {
    if (!/\.(?:t|j)sx?$/.test(path)) return false;
    for (const needle of FAST_FILTER_NEEDLES) {
      if (content.includes(needle)) return true;
    }
    return false;
  },
  extract(input): IExtractOutput {
    const nodes: INode[] = [];
    const edges: IEdge[] = [];
    const sf = parse(input);
    if (!sf) return { nodes, edges };

    const visit = (node: ts.Node): void => {
      if (ts.isClassDeclaration(node) && node.name) {
        const decorators = collectDecorators(node);
        for (const d of decorators) {
          const subtype = DECORATOR_TO_SUBTYPE[d.name];
          if (!subtype) continue;
          const extra = extractDecoratorMetadata(d, subtype);
          const entity = makeEntity(input, node.name.text, subtype, extra);
          nodes.push(entity);
          edges.push(edge(input.fileNodeId, entity.id, EdgeKind.FrameworkDeclares, { subtype }));
          // A class can only carry one Angular role decorator in
          // practice; if a future class somehow has two we'd over-count
          // but the IDs are deterministic so duplicates collapse.
          break;
        }
      }
      ts.forEachChild(node, visit);
    };
    ts.forEachChild(sf, visit);
    return { nodes, edges };
  },
};

// ── helpers ─────────────────────────────────────────────────────────

interface IDecoratorInfo {
  name: string;
  callArguments?: ts.NodeArray<ts.Expression>;
}

function collectDecorators(node: ts.Node): readonly IDecoratorInfo[] {
  if (!ts.canHaveDecorators(node)) return [];
  const decorators = ts.getDecorators(node) ?? [];
  const out: IDecoratorInfo[] = [];
  for (const d of decorators) {
    const expr = d.expression;
    if (ts.isCallExpression(expr) && ts.isIdentifier(expr.expression)) {
      out.push({ name: expr.expression.text, callArguments: expr.arguments });
    } else if (ts.isIdentifier(expr)) {
      out.push({ name: expr.text });
    }
  }
  return out;
}

function extractDecoratorMetadata(d: IDecoratorInfo, subtype: string): Readonly<Record<string, unknown>> {
  if (!d.callArguments || d.callArguments.length === 0) return {};
  const arg0 = d.callArguments[0];
  if (!arg0 || !ts.isObjectLiteralExpression(arg0)) return {};
  const out: Record<string, unknown> = {};
  for (const prop of arg0.properties) {
    if (!ts.isPropertyAssignment(prop)) continue;
    if (!ts.isIdentifier(prop.name)) continue;
    const key = prop.name.text;
    const value = prop.initializer;
    // Lift the most useful string fields. Arrays of identifiers (e.g.
    // `imports: [CommonModule, MyOtherModule]`) become arrays of names.
    if (ts.isStringLiteral(value) || ts.isNoSubstitutionTemplateLiteral(value)) {
      if (subtype === 'component' && (key === 'selector' || key === 'templateUrl' || key === 'styleUrl')) {
        out[key] = value.text;
      } else if (subtype === 'directive' && key === 'selector') {
        out[key] = value.text;
      } else if (subtype === 'pipe' && key === 'name') {
        out[key] = value.text;
      }
    } else if (value.kind === ts.SyntaxKind.TrueKeyword || value.kind === ts.SyntaxKind.FalseKeyword) {
      if (key === 'standalone') out['standalone'] = value.kind === ts.SyntaxKind.TrueKeyword;
    } else if (ts.isArrayLiteralExpression(value)) {
      if (subtype === 'module' && (key === 'imports' || key === 'declarations' || key === 'providers' || key === 'exports')) {
        out[key] = arrayOfIdentifierNames(value);
      } else if (subtype === 'component' && key === 'imports') {
        out[key] = arrayOfIdentifierNames(value);
      }
    }
  }
  return out;
}

function arrayOfIdentifierNames(arr: ts.ArrayLiteralExpression): string[] {
  const out: string[] = [];
  for (const el of arr.elements) {
    if (ts.isIdentifier(el)) out.push(el.text);
  }
  return out;
}

function makeEntity(
  input: IExtractInput,
  className: string,
  subtype: string,
  extra: Readonly<Record<string, unknown>>,
): INode {
  return {
    id: `framework:angular:${subtype}:${input.filePath}#${className}`,
    kind: NodeKind.FrameworkEntity,
    label: className,
    path: input.filePath,
    tags: ['angular', subtype],
    data: { framework: 'angular', subtype, className, ...extra },
  };
}

function edge(
  from: string,
  to: string,
  kind: EdgeKind,
  data?: Readonly<Record<string, unknown>>,
): IEdge {
  return {
    id: createHash('sha1').update(`${from}|${to}|${kind}`).digest('hex'),
    from,
    to,
    kind,
    source: ANGULAR_EXTRACTOR_SOURCE,
    ...(data ? { data } : {}),
  };
}

function parse(input: IExtractInput): ts.SourceFile | undefined {
  const ext = nodePath.extname(input.filePath).toLowerCase();
  const kind =
    ext === '.tsx' ? ts.ScriptKind.TSX
    : ext === '.jsx' ? ts.ScriptKind.JSX
    : ext === '.js' || ext === '.mjs' || ext === '.cjs' ? ts.ScriptKind.JS
    : ts.ScriptKind.TS;
  try {
    return ts.createSourceFile(input.filePath, input.content, ts.ScriptTarget.Latest, true, kind);
  } catch {
    return undefined;
  }
}
